ssh.tunnel.enabled=true
ssh.host=75.119.154.239
ssh.port=22
ssh.username=root
ssh.password=8zGdnPrHkl6vWUl1MG5
ssh.local.port=5433
ssh.remote.host=localhost
ssh.remote.port=5432
ssh.strict.host.key.checking=no

db.url=jdbc:postgresql://localhost:5433/mihilchem
db.username=mihilchem
db.password=mihilchem

user.details.truncate.tables=master_user_levels

user.default.url=http://75.119.154.239/admin
admin.username=groupa
admin.password=123456
