package com.ucsc.tutionplatform.tests;

import java.util.HashMap;
import java.util.Map;

import com.ucsc.tutionplatform.core.DriverManager;
import com.ucsc.tutionplatform.database.DatabaseHandler;
import com.ucsc.tutionplatform.models.TestData;
import com.ucsc.tutionplatform.utils.JsonHandler;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.testng.annotations.AfterClass;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.DataProvider;
import org.testng.annotations.Test;
import org.testng.asserts.SoftAssert;

import java.io.IOException;
import java.lang.reflect.Method;
import java.net.URISyntaxException;
import java.net.URL;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Comparator;
import java.util.List;
import java.util.stream.Stream;

public class BaseTest {

    private final ThreadLocal<SoftAssert> softAssert = new ThreadLocal<>();
    protected final String assertionPath;

    protected BaseTest(String assertionPath) {
        this.assertionPath = assertionPath;
    }

    @BeforeClass(alwaysRun = true)
    public void openBrowser() {

        boolean headless = Boolean.parseBoolean(
                System.getProperty("headless", "false"));

        ChromeOptions options = new ChromeOptions();

        // Added to disable Chrome password manager / password leak warning popup
        Map<String, Object> prefs = new HashMap<>();
        prefs.put("credentials_enable_service", false);
        prefs.put("profile.password_manager_enabled", false);
        prefs.put("profile.password_manager_leak_detection", false);

        options.setExperimentalOption("prefs", prefs);

        if (headless) {
            options.addArguments("--headless=new");
            options.addArguments("--no-sandbox");
            options.addArguments("--disable-dev-shm-usage");
            options.addArguments("--window-size=1920,1080");
        }

        DriverManager.setDriver(new ChromeDriver(options));

        if (!headless) {
            driver().manage().window().maximize();
        }
    }

    @AfterClass(alwaysRun = true)
    public void quitBrowser() {
        DriverManager.quitDriver();
    }

    @BeforeMethod(alwaysRun = true)
    public void initSoftAssert() {
        softAssert.set(new SoftAssert());
    }

    @AfterMethod(alwaysRun = true)
    public void assertAll() {
        try {
            getSoftAssert().assertAll();
        } finally {
            softAssert.remove();
        }
    }

    protected WebDriver driver() {
        return DriverManager.getDriver();
    }

    protected SoftAssert getSoftAssert() {
        SoftAssert currentSoftAssert = softAssert.get();

        if (currentSoftAssert == null) {
            throw new IllegalStateException("SoftAssert is not initialized for the current test method");
        }

        return currentSoftAssert;
    }

    protected void truncateTables(String tableNames) {
        if (tableNames == null || tableNames.isBlank()) {
            return;
        }

        for (String tableName : tableNames.split(",")) {
            String trimmedTableName = tableName.trim();

            if (!trimmedTableName.isEmpty()) {
                DatabaseHandler.truncateTable(trimmedTableName);
            }
        }
    }

    protected void insertCsvDataFromResourceDirectory(String resourceDirectoryPath) {
        URL resourceUrl = BaseTest.class.getClassLoader().getResource(resourceDirectoryPath);

        if (resourceUrl == null) {
            throw new IllegalArgumentException("Insert resource directory not found: " + resourceDirectoryPath);
        }

        try (Stream<Path> paths = Files.list(Path.of(resourceUrl.toURI()))) {
            paths.filter(Files::isRegularFile)
                    .filter(path -> path.getFileName().toString().endsWith(".csv"))
                    .sorted(Comparator.comparing(path -> path.getFileName().toString()))
                    .forEach(path -> insertCsvData(resourceDirectoryPath, path));
        } catch (IOException | URISyntaxException exception) {
            throw new IllegalStateException("Unable to read insert resource directory: " + resourceDirectoryPath, exception);
        }
    }

    private void insertCsvData(String resourceDirectoryPath, Path csvPath) {
        String fileName = csvPath.getFileName().toString();
        String tableName = fileName.substring(0, fileName.length() - ".csv".length());
        String resourcePath = resourceDirectoryPath + "/" + fileName;

        DatabaseHandler.bulkInsertFromCsv(tableName, resourcePath);
        DatabaseHandler.resetAutoGeneratedColumns(tableName);
    }

    @DataProvider
    public Object[][] commonDataProvider(Method method){
        String testCaseId = method.getAnnotation(Test.class).description();
        List<TestData> testDataList = JsonHandler.getTestDataListById(assertionPath, testCaseId);
        Object[][] testDataArray = new Object[testDataList.size()][1];

        for (int index = 0; index < testDataList.size(); index++) {
            testDataArray[index][0] = testDataList.get(index);
        }

        return testDataArray;
    }
}